apiVersion: 1

datasources:
  - name: InfluxDB Logs
    uid: influxdb-logs
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: my-org
      defaultBucket: logs
      tlsSkipVerify: true
    secureJsonData:
      token: <add your influxdb token here>